// Generated by Wrangler on Sun Aug 11 2024 14:00:39 GMT+0000 (Coordinated Universal Time)
// by running `wrangler types`

interface Env {
    BUCKET: R2Bucket
    DB: D1Database
    NODE_ENV?: 'development' | 'production'
}
